apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: op-operator-appserver-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: op-operator-appserver-role-binding
subjects:
  - kind: ServiceAccount
    name: op-operator-appserver-controller-manager
    namespace: op-operator-appserver-system
roleRef:
  kind: ClusterRole
  name: op-operator-appserver-role
  apiGroup: rbac.authorization.k8s.io
