# permissions for end users to view djappservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: djappserver-viewer-role
rules:
- apiGroups:
  - apps.dj-appserver.com
  resources:
  - djappservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dj-appserver.com
  resources:
  - djappservers/status
  verbs:
  - get
