# permissions for end users to edit djappservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: djappserver-editor-role
rules:
- apiGroups:
  - apps.dj-appserver.com
  resources:
  - djappservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dj-appserver.com
  resources:
  - djappservers/status
  verbs:
  - get
