---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.dj-appserver.com
  resources:
  - djappservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dj-appserver.com
  resources:
  - djappservers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.dj-appserver.com
  resources:
  - djappservers/status
  verbs:
  - get
  - patch
  - update
